### ISSUE TITLE
issue to connect

### ISSUE THREAD

**Issue by olivierjag2** [dahlb/ha_kia_hyundai#43]
when I try to connect the integration, with kia ou Hyundai canada (I have both car) I have this error

![image](https://user-images.githubusercontent.com/31319364/147369507-f4bc7170-f230-45e7-9271-82d5703a35f4.png)

**Comment by dahlb** [comment]
@olivierjag2 thanks for filing this ticket about the trouble you're having.  It makes sense the kia and hyundai errors are the same they are nearly identical code within the CA region.

can you try it again after enabling debug logging for this integration

To enable logging, update your configuration.yaml like this, we can get more information in Configuration -> Logs page

```
logger:
  default: warning
  logs:
    custom_components.ha_kia_hyundai: debug
    kia_hyundai_api: debug
```

then attach/paste here the logs generated during the configuration flow. _**be_sure to remove the credentials from the logs you share**_

I am US/Kia so I haven't been able to test those code paths yet; but it is likely a simple typo I can fix within a few hours with the logs.

**Comment by dahlb** [comment]
@olivierjag2 Please try again with the latest code in master.  I was able to reproduce the error you reported even with my invalid credentials, so I've fixed a couple syntax issues; hopefully that'll be all of them.

**Comment by olivierjag2** [comment]
hello, same error after a modify file

here the log:

Logger: aiohttp.server
Source: custom_components/ha_kia_hyundai/api_cloud_ca.py:62 
Integration: Kia/Hyundai (documentation, issues) 
First occurred: 15:56:18 (1 occurrences) 
Last logged: 15:56:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 140, in async_step_auth
    self.data[CONF_VEHICLES] = await api_cloud.get_vehicles()
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 32, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 62, in get_vehicles
    api_vehicles = await self.api.get_vehicles(access_token=access_token)
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 146, in get_vehicles
    await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 33, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 119, in _post_request_with_logging_and_errors_raised
    pin = json_body.get("pin")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dahlb** [comment]
thanks for providing the logs, that error was in the [api package](https://github.com/dahlb/kia_hyundai_api) this integration uses, I've fixed it there and updated master to use the fixed version of the package, please pull down the change to manifest.json from master and try it again.

**Comment by rforbessr** [comment]
Not sure if this should go here but I have a similar issue only in the US - I am unable to setup the vehicle - I get 'Unknown Error Occurred" I have snipped what I found in the logs. 

Thanks




Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 144, in async_step_auth
    await api_cloud.cleanup()
UnboundLocalError: local variable 'api_cloud' referenced before assignment
2021-12-24 22:30:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 132, in async_step_auth
    api_cloud = api_cloud_class(
TypeError: __init__() missing 1 required positional argument: 'pin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 144, in async_step_auth
    await api_cloud.cleanup()
UnboundLocalError: local variable 'api_cloud' referenced before assignment

**Comment by dahlb** [comment]
@rforbessr thanks for posting your logs, if you pull down the latest code those two errors from your logs should be resolved.

if your interested in the code changes generated from your logs:
- the first error is the one [I fixed yesterday](https://github.com/dahlb/ha_kia_hyundai/commit/4da270af016280ff3005a22201208d2ccd4439f7) 
- the second error was caused by the first but I missed it when I fixed the other error so now I've improved the code flow during an [unexpected error](https://github.com/dahlb/ha_kia_hyundai/commit/9820c1d8999cd92afc3bfdf12d2fb3af0bee9e03)

**Comment by olivierjag2** [comment]
now I can connect but I can not choose the car
![image](https://user-images.githubusercontent.com/31319364/147408925-325bc520-fd0a-401b-a302-e29185ebfc88.png)

**Comment by dahlb** [comment]
@olivierjag2 thank you for your patience, I pushed a [fix](https://github.com/dahlb/ha_kia_hyundai/commit/95e5ed51654dbe3efb37fd0e4c4832e95acad096) that should now populate the list of vehicles.  

I needed a sample response to get that fix working but was able to find one in the api package's documentation.  If you run into another error your debug logs could be very helpful.

**Comment by dahlb** [comment]
@olivierjag2 thank you for your patience, I pushed a [fix](https://github.com/dahlb/ha_kia_hyundai/commit/95e5ed51654dbe3efb37fd0e4c4832e95acad096) that should now populate the list of vehicles.  

I needed a sample response to get that fix working but was able to find one in the api package's documentation.  If you run into another error your debug logs could be very helpful.

**Comment by olivierjag2** [comment]
ok thx
now this error message

![image](https://user-images.githubusercontent.com/31319364/147471940-69819b11-a68b-459d-b158-744ca9324d1c.png)


Logger: custom_components.ha_kia_hyundai.vehicle
Source: custom_components/ha_kia_hyundai/util.py:56 
Integration: Kia/Hyundai (documentation, issues) 
First occurred: 07:28:48 (2 occurrences) 
Last logged: 07:29:03

Unexpected error fetching Vehicle xxxxxxxxxxxx data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/config/custom_components/ha_kia_hyundai/util.py", line 53, in safely_get_json_value
    value = value[x]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 112, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 32, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 180, in update
    vehicle.ev_remaining_range_value = safely_get_json_value(
  File "/config/custom_components/ha_kia_hyundai/util.py", line 56, in safely_get_json_value
    value = value[int(x)]
TypeError: 'NoneType' object is not subscriptable

**Comment by dahlb** [comment]
@olivierjag2 thanks for continuing to debug this with me, I pushed a [fix](https://github.com/dahlb/ha_kia_hyundai/commit/fd8904f34a9dfd7ba4cd333f2bc8211eaf2a3f43) that should resolve that to master.

fyi: that error was from the integration attempting to populate sensors that only exist on electric vehicles but shouldn't show up for your vehicle.

**Comment by jakecolman** [comment]
I installed your repo today (presumably has your latest fix) and I am not getting back a list of vehicles to select.  My sample response is as follows:

2021-12-28 11:25:36 DEBUG (MainThread) [kia_hyundai_api.us_kia] response text:{"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"},"payload":{"vehicleSummary":[{"vin":"KNDCC3LC7L5428408","vehicleIdentifier":"428408","modelName":"NIRO","modelYear":"2020","nickName":"Niro","generation":2,"extColorCode":"C3U","trim":"TOURING","imagePath":{"imageName":"2020-niro-touring-c3u.png","imagePath":"/content/dam/kia/us/owners/image/vehicle-app/2020/niro/touring/","imageType":"1","imageSize":{"length":"100","width":"100","uom":0}},"enrollmentStatus":0,"fatcAvailable":0,"telematicsUnit":1,"fuelType":3,"colorName":"DEEP CERULEAN","activationType":2,"mileage":"0","dealerCode":"PA004","mobileStore":[{"osType":0,"downloadURL":"https://itunes.apple.com/us/app/kia-access-with-uvo-link/id1280548773?mt=8","image":{"imageName":"iosImage.png","imagePath":"/content/dam/kia/us/owners/image/common/app/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}},{"osType":1,"downloadURL":"https://play.google.com/store/apps/details?id=com.myuvo.link","image":{"imageName":"androidImage.png","imagePath":"/content/dam/kia/us/owners/image/common/app/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}}],"supportedApp":{"appType":"5","appImage":{"imageName":"uvo-app.png","imagePath":"/content/dam/kia/us/owners/image/common/app/access/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}},"licensePlate":"","psi":"","supportAdditionalDriver":0,"customerType":1,"projectCode":"DEHEV","headUnitDesc":"DAV2","provStatus":"4","enrollmentSuppressionType":0,"vehicleKey":"e6177de1-9003-45f9-a91c-66d9a738ca83"}]}}

**Comment by dahlb** [comment]
@jakecolman I pushed a [fix](https://github.com/dahlb/ha_kia_hyundai/commit/d49319eee969419274477874193ec1d9dbf7528b) that should resolve the issue you had.  In my zeal to support other regions/brands then us kia I introduced a regression.

**Comment by jakecolman** [comment]
Thanks.  That was quick!  How quickly does HACS refresh with the newer repo?

**Comment by dahlb** [comment]
@jakecolman I'm not sure about HACS, but I think it directly interacts with github so there shouldn't be a delay unless it's caching, if the update doesn't show up in HACS try restarting HA to clear any caching HACS might be doing.

**Comment by jakecolman** [comment]
@dahlb HACS shows 1.3.2 as latest available from 3 days ago. I'm wondering whether you need to "publish" in some way for HACS to see it rather than just commit to master. I could just pull the code but I'd prefer letting hacsy manage it, if I can.

**Comment by dahlb** [comment]
@jakecolman select master as the version in hacs for the latest changes, versions are currently only released on a schedule twice a week.
<img width="594" alt="Screen Shot 2021-12-28 at 8 35 03 PM" src="https://user-images.githubusercontent.com/54117/147619195-a99c49ac-1c98-4021-a71b-e06cfacebeca.png">

**Comment by jakecolman** [comment]
Yes, that worked. I didn't realize I could select master as the version.
The issues I reported are resolved. Thanks.

**Comment by dahlb** [comment]
@olivierjag2 @rforbessr are either of you still having any trouble installing the integration? otherwise I'm going to close this ticket.

**Comment by rforbessr** [comment]
Here is my log - The initial set up works - I can now see the integration but it has an error "Retrying setup: Could not convert string to float: "LO"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 138, in async_step_auth
    await api_cloud.login()
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_hyundai.py", line 63, in login
    self._access_token, _, _ = await self.api.login(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/us_hyundai.py", line 155, in login
    await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/us_hyundai.py", line 27, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/us_hyundai.py", line 123, in _post_request_with_logging_and_errors_raised
    return await self.api_session.post(url=url, json=json_body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telematics.hyundaiusa.com:443 ssl:default [Connection reset by peer]
2021-12-30 13:01:02 ERROR (MainThread) [custom_components.ha_kia_hyundai.vehicle] Unexpected error fetching Vehicle MyVINNumberRedacted data: could not convert string to float: 'LO'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 112, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_hyundai.py", line 297, in update
    vehicle.climate_temperature_value = safely_get_json_value(
  File "/config/custom_components/ha_kia_hyundai/util.py", line 61, in safely_get_json_value
    value = callable_to_cast(value)
ValueError: could not convert string to float: 'LO'
2021-12-30 13:01:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'PALISADE (PALISADE)' for ha_kia_hyundai integration not ready yet: could not convert string to float: 'LO'; Retrying in background
2021-12-30 13:01:12 ERROR (MainThread) [custom_components.ha_kia_hyundai.vehicle] Unexpected error fetching Vehicle MyVINNumberRedacted data: could not convert string to float: 'LO'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 112, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_hyundai.py", line 297, in update
    vehicle.climate_temperature_value = safely_get_json_value(
  File "/config/custom_components/ha_kia_hyundai/util.py", line 61, in safely_get_json_value
    value = callable_to_cast(value)
ValueError: could not convert string to float: 'LO'
2021-12-30 13:01:25 ERROR (MainThread) [custom_components.ha_kia_hyundai.vehicle] Unexpected error fetching Vehicle MyVINNumberRedacted data: could not convert string to float: 'LO'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 112, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_hyundai.py", line 297, in update
    vehicle.climate_temperature_value = safely_get_json_value(
  File "/config/custom_components/ha_kia_hyundai/util.py", line 61, in safely_get_json_value
    value = callable_to_cast(value)
ValueError: could not convert string to float: 'LO'

**Comment by jakecolman** [comment]
The installation is working fine and I can see all the sensors.  Thanks.

**Comment by dahlb** [comment]
@rforbessr I think your latest error is fixed in https://github.com/dahlb/ha_kia_hyundai/commit/d77c0e233954bdca3251282a2f94b96501f9e483 Ensure you're using version master from HACS to get that fix quickly.  

I am sorry, I didn't mean to rush you, especially during the holidays.  This ticket has sprawled a bit and I wanted to make sure everything in it was addressed, and I was optimistic that the earlier fixes handled everything :)

PS: I am still new to github, but I think if I close an issue early you can still comment on it and I can reopen :)

**Comment by rforbessr** [comment]
No worries- not sure what happen but after about three or four hours it just worked - weird - I’ll let you know if I see anything else

**Comment by dahlb** [comment]
It likely started working because the error you had was for an edge case
temperature, if the temperature went up that would've taken you out of the
edge case of LO (low) temperature. Still the updated code should handle
when the temperature goes down again :)
